[workspace]
resolver = "2"
members = [
    "crates/cdhit-core",
    "crates/cdhit-cli",
    "crates/cdhit-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"
repository = "https://github.com/seanrjohnson-neb/cdhit-rust"

[profile.release]
opt-level = 3
lto = true
